### ISSUE TITLE
setup auto updating for www2. and www.

### ISSUE THREAD

**Issue by VonSub** [harvested-io/www_harvested.io#4]
I updated some links and removed some buttons. but it is not reflecting.

**Comment by PeterNashaat** [comment]
- webhook is working now for both www2 and www

**Comment by VonSub** [comment]
updated www2 twice today, changes not showing on site

**Comment by PeterNashaat** [comment]
- checked the webhook , should be working 

![image](https://user-images.githubusercontent.com/13523434/56565623-23750880-65b1-11e9-861d-d9d898178e44.png)
